name: flutter_code_authentication_module
description: "FlutterCode's authentication package."
repository: "https://github.com/helpis-software/flutter_code/packages/features/authentication"
homepage: "https://flutter_code.helpis.dev"
version: 1.0.0+1
publish_to: none

# dart pub global activate derry
scripts:
  flavors: flutter pub run flutter_flavorizr
  regenerate_goldens: flutter test --update-goldens --tags=golden
  gen_build: flutter pub run build_runner build --delete-conflicting-outputs
  gen_watch: flutter pub run build_runner watch --delete-conflicting-output
  translate: helpis translate -n flutter_code --locales=el,en --fallbackLocale=el -t packages/common/config/localization/ && dart fix --apply
  store: helpis createStore -n flutter_code --keys=darkMode-true,locale-Language.el.name && dart fix --apply

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  auth_buttons: ^3.0.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_data: ^1.5.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  handy_window: ^0.1.9
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_api: ^5.2.0
  path_provider: ^2.0.11
  phone_form_field: ^7.0.5
  platform: ^3.1.0
  riverpod_annotation: ^1.0.6
  shared_preferences: ^2.0.15
  state_notifier: ^0.7.2+1
  universal_io: ^2.0.4
  upgrader: ^5.0.0
  uuid: ^3.0.7


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_goldens:
    sdk: flutter
  integration_test:
    sdk: flutter
  bdd_widget_test: ^1.4.3
  build_runner: ^2.3.0
  freezed: ^2.2.0
  golden_toolkit: ^0.14.0
  icons_launcher: ^2.0.6
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  riverpod_generator: ^1.0.6
  spec: ^0.2.2
  test: ^1.21.4

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
#   generate: true
  assets:
    - assets/
    - assets/image/
    - assets/image/vector/
    - assets/image/raster/
    - assets/multimedia/
    - assets/multimedia/audio/
    - assets/multimedia/video/
    - assets/pdf/
    - assets/font/
    - assets/color/
    - assets/txt/
    - assets/animation/
    - assets/animation/rive/
    - assets/animation/lottie/
#  fonts:
#    - family: Comfortaa
#      fonts:
#        - asset: assets/fonts/comfortaa.ttf


flavorizr:
  ide: idea
  instructions: [
      assets:download,
      assets:extract,
      assets:clean,
      android:buildGradle,
      android:androidManifest,
      android:icons,
      ios:icons,
      ios:plist
  ]
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    development:
      app:
        name: development
      android:
        applicationId: "dev.helpis.flutter_code"
      ios:
        bundleId: "dev.helpis.flutter_code"
  production:
      app:
        name: production
      android:
        applicationId: "dev.helpis.flutter_code"
      ios:
        bundleId: "dev.helpis.flutter_code"
  staging:
      app:
        name: staging
      android:
        applicationId: "dev.helpis.flutter_code"
      ios:
        bundleId: "dev.helpis.flutter_code"


# flutter_gen:
#   output: packages/common/gen/
#   line_length: 80
#   gen_for_package: true
#   integrations:
#     flutter_svg: true
#   assets:
#     enabled: true
#   fonts:
#     enabled: true
#   colors:
#     enabled: true
#     inputs:
#       - assets/color/colors.xml
