name: flutter_code
repository: https://github.com/helpis-software/flutter_code
packages:
  - packages/**
  - .

ignore:
  - 'packages/**/example'
  - 'packages/**/examples'
  - 'examples'

sdkPath: auto
command:
  bootstrap:
    usePubspecOverrides: true
  version:
    includeCommitId: true
    linkToCommits: true
    workspaceChangelog: true
    updateGitTagRefs: true
    includeScopes: true
    branch: main
scripts:
  config:
    select-package:
      flutter: true
    exec: "flutter config --enable-web --enable-macos-desktop --enable-linux-desktop --enable-windows-desktop --enable-ios --enable-android --single-widget-reload-optimization"
  get:
    exec: flutter pub get
  upgrade:
    exec: flutter pub upgrade
  upgradeMajor:
    exec: flutter pub upgrade --major-versions
  format_check:
    exec: dart format --set-exit-if-changed .
  format:
    exec: dart format --fix .
  lint:
    exec: dart fix --dry-run
  fix:
    exec: dart fix --apply
  analyze:
    exec: dart analyze --fatal-infos
  test:
    exec: flutter test
  test_integration:
    select-package:
      flutter: true
    exec: flutter drive
  test_benchmark:
    select-package:
      flutter: true
    exec: flutter test test_benchmark
  test_goldens:
    select-package:
      flutter: true
    exec: flutter test --update-goldens --tags=golden test_goldens
  test_coverage:
    select-package:
      flutter: true
    exec: flutter test --coverage --merge-coverage --no-pub
  gen_coverage:
    exec: "$MELOS_ROOT_PATH/scripts/combine_coverage.sh"
  gen_html_coverage:
    exec: "genhtml $MELOS_ROOT_PATH/coverage/lcov.info -o $MELOS_ROOT_PATH/coverage/html"
  build_debug:
    exec: flutter build -v $1
  build_release:
    exec: flutter build -v --release $1
  fastlane:
    run: bundle exec fastlane $1
